using System.Collections.Generic;
using System.Linq;

namespace Mutzl.Homeassistant
{
    public class HoerzuStation
    {
        private HoerzuStation(int id, string name)
        {
            Id = id;
            Name = name;
        }

        public int Id { get; }
        public string Name { get; }

        public static HoerzuStation? GetByName(string name) => GetAll().SingleOrDefault(item => item.Name == name);
        public static HoerzuStation? GetById(int id) => GetAll().SingleOrDefault(item => item.Id == id);

        public static IEnumerable<HoerzuStation> GetAll()
        {
            return new[]
            {
                new HoerzuStation(71, "Das Erste"),
                new HoerzuStation(37, "ZDF"),
                new HoerzuStation(38, "RTL"),
                new HoerzuStation(39, "Sat.1"),
                new HoerzuStation(40, "ProSieben"),
                new HoerzuStation(41, "RTL Zwei"),
                new HoerzuStation(44, "kabel eins"),
                new HoerzuStation(42, "VOX"),
                new HoerzuStation(56, "3sat"),
                new HoerzuStation(58, "Arte"),
                new HoerzuStation(43, "Super RTL"),
                new HoerzuStation(57, "KiKA"),
                new HoerzuStation(46, "WDR"),
                new HoerzuStation(47, "NDR"),
                new HoerzuStation(48, "MDR"),
                new HoerzuStation(50, "SWR"),
                new HoerzuStation(49, "HR"),
                new HoerzuStation(52, "RBB"),
                new HoerzuStation(51, "BR"),
                new HoerzuStation(104, "ARD alpha"),
                new HoerzuStation(153, "Hamburg 1"),
                new HoerzuStation(1192, "TV.Berlin"),
                new HoerzuStation(151, "Franken Fernsehen"),
                new HoerzuStation(211, "Rhein-Neckar-Fernsehen"),
                new HoerzuStation(403, "rheinmainTV"),
                new HoerzuStation(262, "München TV"),
                new HoerzuStation(66, "n-tv"),
                new HoerzuStation(175, "WELT"),
                new HoerzuStation(194, "Phoenix"),
                new HoerzuStation(65, "Eurosport 1"),
                new HoerzuStation(64, "SPORT1"),
                new HoerzuStation(139, "Disney Channel"),
                new HoerzuStation(277, "Tele 5"),
                new HoerzuStation(660, "Servus TV"),
                new HoerzuStation(694, "sixx"),
                new HoerzuStation(507, "DMAX"),
                new HoerzuStation(159, "HSE"),
                new HoerzuStation(208, "QVC"),
                new HoerzuStation(146, "One"),
                new HoerzuStation(100, "tagesschau24"),
                new HoerzuStation(659, "ZDFneo"),
                new HoerzuStation(276, "ZDFinfo"),
                new HoerzuStation(280, "Bibel TV"),
                new HoerzuStation(54, "ORF 1"),
                new HoerzuStation(55, "ORF 2"),
                new HoerzuStation(757, "ORF 3"),
                new HoerzuStation(759, "ORF Sport +"),
                new HoerzuStation(115, "ATV"),
                new HoerzuStation(761, "ATV2"),
                new HoerzuStation(402, "Puls 4"),
                new HoerzuStation(769, "sixx Austria"),
                new HoerzuStation(59, "SRF 1"),
                new HoerzuStation(60, "SRF 2"),
                new HoerzuStation(260, "TV5MONDE"),
                new HoerzuStation(252, "TF1"),
                new HoerzuStation(149, "France 2"),
                new HoerzuStation(150, "France 3"),
                new HoerzuStation(610, "Sky Cinema Premieren"),
                new HoerzuStation(612, "Sky Cinema Premieren +24"),
                new HoerzuStation(613, "Sky Cinema Action"),
                new HoerzuStation(617, "Sky Cinema Fun"),
                new HoerzuStation(12132, "Sky Cinema Thriller"),
                new HoerzuStation(618, "Sky Cinema Best Of"),
                new HoerzuStation(614, "Sky Cinema Classics"),
                new HoerzuStation(12042, "Sky Cinema Family"),
                new HoerzuStation(12121, "Sky Cinema Special"),
                new HoerzuStation(615, "Sky Krimi"),
                new HoerzuStation(619, "Sky Sport 1"),
                new HoerzuStation(620, "Sky Sport 2"),
                new HoerzuStation(561, "Sky Sport F1"),
                new HoerzuStation(622, "Sky Sport Austria 1"),
                new HoerzuStation(623, "Sky Sport Bundesliga 1"),
                new HoerzuStation(471, "13TH STREET"),
                new HoerzuStation(472, "Syfy"),
                new HoerzuStation(565, "FOX"),
                new HoerzuStation(590, "TNT Serie"),
                new HoerzuStation(633, "TNT Film"),
                new HoerzuStation(468, "Sony AXN"),
                new HoerzuStation(450, "Kinowelt TV"),
                new HoerzuStation(451, "Silverline"),
                new HoerzuStation(766, "Sat.1 emotions"),
                new HoerzuStation(492, "kabel eins classics"),
                new HoerzuStation(527, "RTL Crime"),
                new HoerzuStation(528, "RTL Living"),
                new HoerzuStation(763, "NITRO"),
                new HoerzuStation(529, "RTL Passion"),
                new HoerzuStation(552, "Romance TV"),
                new HoerzuStation(487, "Gute Laune TV"),
                new HoerzuStation(152, "GoldStar TV"),
                new HoerzuStation(154, "Heimatkanal"),
                new HoerzuStation(195, "doxx"),
                new HoerzuStation(453, "National Geographic"),
                new HoerzuStation(626, "National Geographic Wild"),
                new HoerzuStation(138, "Discovery Channel"),
                new HoerzuStation(1183, "Animal Planet"),
                new HoerzuStation(452, "History"),
                new HoerzuStation(756, "Spiegel TV Wissen"),
                new HoerzuStation(625, "Spiegel Geschichte"),
                new HoerzuStation(460, "Disney Junior"),
                new HoerzuStation(493, "Boomerang"),
                new HoerzuStation(160, "Junior"),
                new HoerzuStation(758, "E! Entertainment"),
                new HoerzuStation(662, "BBC Entertainment"),
                new HoerzuStation(12102, "eSports1"),
                new HoerzuStation(469, "Extreme Sports Channel"),
                new HoerzuStation(463, "Nautical Channel"),
                new HoerzuStation(627, "Motorvision TV"),
                new HoerzuStation(133, "Stingray Classica"),
                new HoerzuStation(70, "MTV"),
                new HoerzuStation(466, "MTV Hits UK"),
                new HoerzuStation(296, "VH1 Classic"),
                new HoerzuStation(464, "Trace.TV"),
                //new SenderItem(621, "Sky Sport 1"),
                //new SenderItem(629, "Sky Cinema Premieren"),
                new HoerzuStation(624, "National Geographic HD"),
                new HoerzuStation(632, "History HD"),
                new HoerzuStation(765, "ProSieben Fun"),
                new HoerzuStation(783, "ProSieben Maxx"),
                new HoerzuStation(774, "Sat.1 Gold"),
                new HoerzuStation(511, "Deluxe Music"),
                new HoerzuStation(68, "Euronews"),
                new HoerzuStation(10157, "Sky Atlantic"),
                new HoerzuStation(698, "SPORT1+"),
                new HoerzuStation(564, "Sportdigital Fußball"),
                new HoerzuStation(504, "Eurosport 2"),
                new HoerzuStation(12035, "TNT Comedy"),
                new HoerzuStation(12033, "RTL Plus"),
                new HoerzuStation(12125, "VOXup"),
            };
        }
    }
}
