using System.Collections.Generic;
using System.Linq;

namespace Mutzl.Homeassistant
{
    public class SenderItem
    {
        private SenderItem(int id, string name)
        {
            Id = id;
            Name = name;
        }

        public int Id { get; }
        public string Name { get; }

        public static SenderItem? GetByName(string name) => GetAll().SingleOrDefault(item => item.Name == name);
        public static SenderItem? GetById(int id) => GetAll().SingleOrDefault(item => item.Id == id);

        public static IEnumerable<SenderItem> GetAll()
        {
            return new[]
            {
                new SenderItem(71, "Das Erste"),
                new SenderItem(37, "ZDF"),
                new SenderItem(38, "RTL"),
                new SenderItem(39, "Sat.1"),
                new SenderItem(40, "ProSieben"),
                new SenderItem(41, "RTL Zwei"),
                new SenderItem(44, "kabel eins"),
                new SenderItem(42, "VOX"),
                new SenderItem(56, "3sat"),
                new SenderItem(58, "Arte"),
                new SenderItem(43, "Super RTL"),
                new SenderItem(57, "KiKA"),
                new SenderItem(46, "WDR"),
                new SenderItem(47, "NDR"),
                new SenderItem(48, "MDR"),
                new SenderItem(50, "SWR"),
                new SenderItem(49, "HR"),
                new SenderItem(52, "RBB"),
                new SenderItem(51, "BR"),
                new SenderItem(104, "ARD alpha"),
                new SenderItem(153, "Hamburg 1"),
                new SenderItem(1192, "TV.Berlin"),
                new SenderItem(151, "Franken Fernsehen"),
                new SenderItem(211, "Rhein-Neckar-Fernsehen"),
                new SenderItem(403, "rheinmainTV"),
                new SenderItem(262, "München TV"),
                new SenderItem(66, "n-tv"),
                new SenderItem(175, "WELT"),
                new SenderItem(194, "Phoenix"),
                new SenderItem(65, "Eurosport 1"),
                new SenderItem(64, "SPORT1"),
                new SenderItem(139, "Disney Channel"),
                new SenderItem(277, "Tele 5"),
                new SenderItem(660, "Servus TV"),
                new SenderItem(694, "sixx"),
                new SenderItem(507, "DMAX"),
                new SenderItem(159, "HSE"),
                new SenderItem(208, "QVC"),
                new SenderItem(146, "One"),
                new SenderItem(100, "tagesschau24"),
                new SenderItem(659, "ZDFneo"),
                new SenderItem(276, "ZDFinfo"),
                new SenderItem(280, "Bibel TV"),
                new SenderItem(54, "ORF 1"),
                new SenderItem(55, "ORF 2"),
                new SenderItem(757, "ORF 3"),
                new SenderItem(759, "ORF Sport +"),
                new SenderItem(115, "ATV"),
                new SenderItem(761, "ATV2"),
                new SenderItem(402, "Puls 4"),
                new SenderItem(769, "sixx Austria"),
                new SenderItem(59, "SRF 1"),
                new SenderItem(60, "SRF 2"),
                new SenderItem(260, "TV5MONDE"),
                new SenderItem(252, "TF1"),
                new SenderItem(149, "France 2"),
                new SenderItem(150, "France 3"),
                new SenderItem(610, "Sky Cinema Premieren"),
                new SenderItem(612, "Sky Cinema Premieren +24"),
                new SenderItem(613, "Sky Cinema Action"),
                new SenderItem(617, "Sky Cinema Fun"),
                new SenderItem(12132, "Sky Cinema Thriller"),
                new SenderItem(618, "Sky Cinema Best Of"),
                new SenderItem(614, "Sky Cinema Classics"),
                new SenderItem(12042, "Sky Cinema Family"),
                new SenderItem(12121, "Sky Cinema Special"),
                new SenderItem(615, "Sky Krimi"),
                new SenderItem(619, "Sky Sport 1"),
                new SenderItem(620, "Sky Sport 2"),
                new SenderItem(561, "Sky Sport F1"),
                new SenderItem(622, "Sky Sport Austria 1"),
                new SenderItem(623, "Sky Sport Bundesliga 1"),
                new SenderItem(471, "13TH STREET"),
                new SenderItem(472, "Syfy"),
                new SenderItem(565, "FOX"),
                new SenderItem(590, "TNT Serie"),
                new SenderItem(633, "TNT Film"),
                new SenderItem(468, "Sony AXN"),
                new SenderItem(450, "Kinowelt TV"),
                new SenderItem(451, "Silverline"),
                new SenderItem(766, "Sat.1 emotions"),
                new SenderItem(492, "kabel eins classics"),
                new SenderItem(527, "RTL Crime"),
                new SenderItem(528, "RTL Living"),
                new SenderItem(763, "NITRO"),
                new SenderItem(529, "RTL Passion"),
                new SenderItem(552, "Romance TV"),
                new SenderItem(487, "Gute Laune TV"),
                new SenderItem(152, "GoldStar TV"),
                new SenderItem(154, "Heimatkanal"),
                new SenderItem(195, "doxx"),
                new SenderItem(453, "National Geographic"),
                new SenderItem(626, "National Geographic Wild"),
                new SenderItem(138, "Discovery Channel"),
                new SenderItem(1183, "Animal Planet"),
                new SenderItem(452, "History"),
                new SenderItem(756, "Spiegel TV Wissen"),
                new SenderItem(625, "Spiegel Geschichte"),
                new SenderItem(460, "Disney Junior"),
                new SenderItem(493, "Boomerang"),
                new SenderItem(160, "Junior"),
                new SenderItem(758, "E! Entertainment"),
                new SenderItem(662, "BBC Entertainment"),
                new SenderItem(12102, "eSports1"),
                new SenderItem(469, "Extreme Sports Channel"),
                new SenderItem(463, "Nautical Channel"),
                new SenderItem(627, "Motorvision TV"),
                new SenderItem(133, "Stingray Classica"),
                new SenderItem(70, "MTV"),
                new SenderItem(466, "MTV Hits UK"),
                new SenderItem(296, "VH1 Classic"),
                new SenderItem(464, "Trace.TV"),
                //new SenderItem(621, "Sky Sport 1"),
                //new SenderItem(629, "Sky Cinema Premieren"),
                new SenderItem(624, "National Geographic HD"),
                new SenderItem(632, "History HD"),
                new SenderItem(765, "ProSieben Fun"),
                new SenderItem(783, "ProSieben Maxx"),
                new SenderItem(774, "Sat.1 Gold"),
                new SenderItem(511, "Deluxe Music"),
                new SenderItem(68, "Euronews"),
                new SenderItem(10157, "Sky Atlantic"),
                new SenderItem(698, "SPORT1+"),
                new SenderItem(564, "Sportdigital Fußball"),
                new SenderItem(504, "Eurosport 2"),
                new SenderItem(12035, "TNT Comedy"),
                new SenderItem(12033, "RTL Plus"),
                new SenderItem(12125, "VOXup"),
            };
        }
    }
}
